# =============================================================================
# PROXMOX BASIC CONFIGURATION
# =============================================================================

# Basic setup
pve_group: pve01  # Host group name
pve_reboot_on_kernel_update: true
pve_run_system_upgrades: true
pve_run_proxmox_upgrades: true
pve_notification_email: "mr.dennis.truong@gmail.com"

# Repository configuration
pve_enterprise_repo_removal: true
pve_no_subscription_repo: true


# Do NOT remove/patch the web UI subscription check banner
pve_remove_subscription_warning: false

# Extra packages (examples)
pve_extra_packages:
  - htop
  - vim
  - curl
  - wget
  - mailutils
  - rsyslog-relp
  - rkhunter
  - chkrootkit
  - aide
  - unattended-upgrades
  # Security packages moved to dedicated security playbook
  # - zfsutils-linux  # Enable if using ZFS

# Configure automatic security updates:
unattended_upgrades_enabled: true
unattended_upgrades_auto_reboot: true
unattended_upgrades_auto_reboot_time: "03:00"

# =============================================================================
# CLUSTERING CONFIGURATION
# =============================================================================

# Cluster settings (set to false for single node)
pve_cluster_enabled: false
# pve_cluster_clustername: "homelab-cluster"  # Uncomment for cluster
# pve_cluster_addr0: "{{ ansible_default_ipv4.address }}"  # Primary network
# pve_cluster_addr1: "{{ ansible_eth1.ipv4.address }}"     # Secondary network (optional)

# =============================================================================
# ZFS CONFIGURATION
# =============================================================================

pve_zfs_enabled: false
# pve_zfs_pools:  # Uncomment if using ZFS
#   - name: "rpool"
#     devices: ["/dev/sda", "/dev/sdb"]
#     raidlevel: "mirror"
#   
# pve_zfs_volumes:
#   - name: "rpool/data"
#     size: "500G"

# =============================================================================
# WATCHDOG CONFIGURATION
# =============================================================================

# Hardware watchdog (use "ipmi" for server hardware, "none" for consumer)
pve_watchdog: "none"
# pve_watchdog: "ipmi"  # Uncomment for server hardware

# =============================================================================
# METRIC SERVERS (MONITORING)
# =============================================================================

# Monitoring integration (examples)
# pve_metric_servers:
#   - id: "influxdb1"
#     server: "monitoring.local"
#     port: 8086
#     type: "influxdb"
#     token: "your-influxdb-token"
#   
#   - id: "graphite1"
#     server: "graphite.local"
#     port: 2003
#     type: "graphite"

# =============================================================================
# SSL CERTIFICATES
# =============================================================================

# Custom SSL certificates (optional)
# pve_ssl_cert_file: "/path/to/certificate.pem"
# pve_ssl_key_file: "/path/to/private.key"
