# GPU Passthrough Configuration
# Requires Intel VT-d support
pve_pcie_passthrough_enabled: true
pve_iommu_passthrough_mode: true
pve_iommu_unsafe_interrupts: false
pve_mediated_devices_enabled: false
pve_pcie_ovmf_enabled: false

# RTX 3080 and its audio controller
pve_pci_device_ids:
  - id: "10de:2206"  # RTX 3080 GPU
  - id: "10de:1aef"  # RTX 3080 Audio

# Blacklist GPU drivers
pve_vfio_blacklist_drivers:
  - name: "nouveau"
  - name: "nvidia"
  - name: "nvidiafb"
  - name: "nvidia-drm"
  - name: "nvidia-modeset"
  - name: "nvidia-uvm"

pve_pcie_ignore_msrs: false
pve_pcie_report_msrs: true